export const CURRENCIES = [
  { code: "AED", name: "United Arab Emirates (AED)" },
  { code: "AFN", name: "Afghanistan (AFN)" },
  { code: "ALL", name: "Albania (ALL)" },
  { code: "ARS", name: "Argentina (ARS)" },
  { code: "AUD", name: "Australia (AUD)" },
  { code: "BAM", name: "Bosnia and Herzegovina (BAM)" },
  { code: "BDT", name: "Bangladesh (BDT)" },
  { code: "BGN", name: "Bulgaria (BGN)" },
  { code: "BHD", name: "Bahrain (BHD)" },
  { code: "BRL", name: "Brazil (BRL)" },
  { code: "CAD", name: "Canada (CAD)" },
  { code: "CHF", name: "Switzerland (CHF)" },
  { code: "CLP", name: "Chile (CLP)" },
  { code: "CNY", name: "China (CNY)" },
  { code: "COP", name: "Colombia (COP)" },
  { code: "CZK", name: "Czech Republic (CZK)" },
  { code: "DKK", name: "Denmark (DKK)" },
  { code: "DZD", name: "Algeria (DZD)" },
  { code: "EGP", name: "Egypt (EGP)" },
  { code: "EUR", name: "European Union (EUR)" },
  { code: "GBP", name: "United Kingdom (GBP)" },
  { code: "GHS", name: "Ghana (GHS)" },
  { code: "HKD", name: "Hong Kong (HKD)" },
  { code: "HRK", name: "Croatia (HRK)" },
  { code: "HUF", name: "Hungary (HUF)" },
  { code: "IDR", name: "Indonesia (IDR)" },
  { code: "ILS", name: "Israel (ILS)" },
  { code: "INR", name: "India (INR)" },
  { code: "ISK", name: "Iceland (ISK)" },
  { code: "JPY", name: "Japan (JPY)" },
  { code: "KES", name: "Kenya (KES)" },
  { code: "KRW", name: "South Korea (KRW)" },
  { code: "KWD", name: "Kuwait (KWD)" },
  { code: "KZT", name: "Kazakhstan (KZT)" },
  { code: "LKR", name: "Sri Lanka (LKR)" },
  { code: "MAD", name: "Morocco (MAD)" },
  { code: "MKD", name: "North Macedonia (MKD)" },
  { code: "MMK", name: "Myanmar (MMK)" },
  { code: "MXN", name: "Mexico (MXN)" },
  { code: "MYR", name: "Malaysia (MYR)" },
  { code: "NGN", name: "Nigeria (NGN)" },
  { code: "NOK", name: "Norway (NOK)" },
  { code: "NPR", name: "Nepal (NPR)" },
  { code: "NZD", name: "New Zealand (NZD)" },
  { code: "OMR", name: "Oman (OMR)" },
  { code: "PEN", name: "Peru (PEN)" },
  { code: "PHP", name: "Philippines (PHP)" },
  { code: "PKR", name: "Pakistan (PKR)" },
  { code: "PLN", name: "Poland (PLN)" },
  { code: "QAR", name: "Qatar (QAR)" },
  { code: "RON", name: "Romania (RON)" },
  { code: "RSD", name: "Serbia (RSD)" },
  { code: "RUB", name: "Russia (RUB)" },
  { code: "SAR", name: "Saudi Arabia (SAR)" },
  { code: "SEK", name: "Sweden (SEK)" },
  { code: "SGD", name: "Singapore (SGD)" },
  { code: "THB", name: "Thailand (THB)" },
  { code: "TND", name: "Tunisia (TND)" },
  { code: "TRY", name: "Turkey (TRY)" },
  { code: "TZS", name: "Tanzania (TZS)" },
  { code: "UAH", name: "Ukraine (UAH)" },
  { code: "UGX", name: "Uganda (UGX)" },
  { code: "USD", name: "United States (USD)" },
  { code: "VND", name: "Vietnam (VND)" },
  { code: "ZAR", name: "South Africa (ZAR)" },
].sort((a, b) => a.name.localeCompare(b.name));
