"use client";

import { useState } from "react";
import { SeoHead } from "@/components/seo-head";
import { Card, Textarea, Button } from "@/components/ui";
import { BrainCircuit, AlertTriangle, ShieldCheck } from "lucide-react";
import { useCheckAiContent } from "@workspace/api-client-react";

export function AiDetector() {
  const [text, setText] = useState("");
  const { mutate, data, isPending, error } = useCheckAiContent();

  const handleCheck = () => {
    if (text.length > 50) {
      mutate({ data: { text } });
    }
  };

  return (
      <>
      <SeoHead title="ZeroGPT AI Content Detector" description="Check if your text was written by AI like ChatGPT or Claude. Best free AI detector." />
      
      <div className="w-full max-w-5xl mx-auto px-4 py-12">
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center p-4 bg-purple-500/10 rounded-2xl mb-6">
            <BrainCircuit className="w-10 h-10 text-purple-500" />
          </div>
          <h1 className="text-4xl font-bold mb-4">AI Content Detector</h1>
          <p className="text-muted-foreground">Paste your text below to analyze if it was generated by AI or written by a human.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_350px] gap-8">
          <Card className="p-6 flex flex-col gap-4">
            <Textarea 
              placeholder="Paste your article, essay, or text here (minimum 50 characters)..." 
              className="min-h-[300px] text-base resize-none border-0 focus-visible:ring-0 p-0"
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
            <div className="flex justify-between items-center border-t border-border pt-4">
              <span className="text-sm text-muted-foreground">{text.length} characters</span>
              <Button 
                onClick={handleCheck} 
                size="lg" 
                disabled={text.length < 50} 
                isLoading={isPending}
                className="bg-purple-600 hover:bg-purple-700"
              >
                Detect AI Content
              </Button>
            </div>
            {error && <p className="text-destructive text-sm text-right">An error occurred during analysis.</p>}
          </Card>

          <div className="space-y-6">
            <Card className="p-6 bg-slate-50 dark:bg-slate-900">
              <h3 className="font-bold text-lg mb-6">Analysis Results</h3>
              
              {!data && !isPending && (
                <div className="text-center py-10 text-muted-foreground text-sm">
                  Waiting for input...
                </div>
              )}

              {isPending && (
                <div className="text-center py-10 text-muted-foreground text-sm animate-pulse">
                  Analyzing text structure and patterns...
                </div>
              )}

              {data && (
                <div className="space-y-8 animate-in fade-in">
                  <div className="text-center">
                    <div className="inline-block p-4 rounded-full bg-white dark:bg-black shadow-sm mb-4">
                      {data.aiScore > 50 ? <AlertTriangle className="w-8 h-8 text-rose-500" /> : <ShieldCheck className="w-8 h-8 text-emerald-500" />}
                    </div>
                    <h4 className="text-2xl font-bold">{data.verdict}</h4>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between text-sm font-medium">
                      <span>AI Generated</span>
                      <span className="text-rose-500">{data.aiScore}%</span>
                    </div>
                    <div className="w-full h-3 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-rose-500 rounded-full" style={{ width: `${data.aiScore}%` }} />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between text-sm font-medium">
                      <span>Human Written</span>
                      <span className="text-emerald-500">{data.humanScore}%</span>
                    </div>
                    <div className="w-full h-3 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-emerald-500 rounded-full" style={{ width: `${data.humanScore}%` }} />
                    </div>
                  </div>
                </div>
              )}
            </Card>

            <div className="ad-banner m-0">
              
            </div>
          </div>
        </div>
      </div>
      </>
  );
}
